### ISSUE TITLE
Générer toutes les attestations

### ISSUE THREAD

**Issue by 7omate** [teymour/attestation-covid19#10]
Bonjour,
Voici un script utilisable pour générer une attestation par heure entre 8h et 22h.
Je l'ai par exemple lancé en l'éditant manuellement 4 fois (travail, famille, sport, santé).
Les attestations sont organisée par thème, par jour, fichier nomé par heure.
Au total ~1400 fichiers pour 180Mo.

```
# lancer par exemple avec $bash <nom_du_script>

# configurer avant de lancer
export MOTIF=sport

export motif_travail=""
export motif_courses=""
export motif_sante=""
export motif_famille=""
export motif_sport="x"
export motif_judiciaire=""
export motif_missions=""

for leday in $(seq 20 1 30)
do
        export DAY="$leday/04/2020"
        export DAY_PATH="2020-04-$leday"
        mkdir -p $MOTIF/$DAY_PATH
        for i in $(seq 8 1 22); do echo $i; export HEURE=$i; touch config/config.inc; make; done
done

for leday in $(seq 1 1 11)
do
        export DAY="$leday/05/2020"
        export DAY_PATH="2020-05-$leday"
        mkdir -p $MOTIF/$DAY_PATH
        for i in $(seq 8 1 22); do echo $i; export HEURE=$i; touch config/config.inc; make; done
done
```

Avec le Makefile légèrement modifié et en enlevant les informations du fichier de configuration.
```
diff --git a/Makefile b/Makefile
index eb94222..a362a13 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 config_file=config/config.inc
-output_file=attestation.pdf
+output_file=$$MOTIF/$$DAY_PATH/attestation-$$HEURE.pdf
```

Merci pour ce travail qui m'a permis de générer une attestation par heure pour me "libérer" de cette contrainte absurde. 
Bien sûr j'ai reçu mon amende de 135€ en allant à la boulangerie à côté de chez moi avant de générer ces fichiers.

**Comment by teymour** [comment]
En fait, il n'y a pas besoin de modifier le Makefile pour votre besoin.

Il est possible de demander à make de prendre en compte la variable d’environnement `output_file` qui contient le chemin vers l'attestation : 

    diff --git a/generator.sh b/generator.sh
    index b4fd938..9a2db30 100644
    --- a/generator.sh
    +++ b/generator.sh
    @@ -16,7 +16,7 @@ do
             export DAY="$leday/04/2020"
             export DAY_PATH="2020-04-$leday"
             mkdir -p $MOTIF/$DAY_PATH
    -        for i in $(seq 8 1 22); do echo $i; export HEURE=$i; touch config/config.inc; make; done
    +        for i in $(seq 8 1 22); do echo $i; export HEURE=$i; touch config/config.inc; output_file=$MOTIF"/"$DAY_PATH"/attestation-"$HEURE".pdf"  make -e; done
     done
     
     for leday in $(seq 1 1 11)
    @@ -24,5 +24,5 @@ do
             export DAY="$leday/05/2020"
             export DAY_PATH="2020-05-$leday"
             mkdir -p $MOTIF/$DAY_PATH
    -        for i in $(seq 8 1 22); do echo $i; export HEURE=$i; touch config/config.inc; make; done
    +        for i in $(seq 8 1 22); do echo $i; export HEURE=$i; touch config/config.inc; output_file=$MOTIF"/"$DAY_PATH"/attestation-"$HEURE".pdf"  make -e; done
     done

Après ca me semble un peu overkill de générer autant d'attestations.

Perso, je me suis fait un lien par motif sur lequel je clique juste avant de sortir et ca me génère mon attestation. La doc pour le faire est dispo dans le README.md du projet.

**Comment by 7omate** [comment]
Merci pour cette suggestion :)
