### ISSUE TITLE
PDFTK Install

### ISSUE THREAD

**Issue by pdewas** [teymour/attestation-covid19#18]
Problem with dependencies and pdftk : 

`E: Package 'pdftk' has no installation candidate`

**Comment by teymour** [comment]
what is your linux distribution (and version) ?

**Comment by pdewas** [comment]
Windows Bash Linux


Le sam. 7 nov. 2020 à 21:17, Tangui Morlier <notifications@github.com> a
écrit :

**Comment by teymour** [comment]
Windows is not supported.
