### ISSUE TITLE
Problème avec le qrcode

### ISSUE THREAD

**Issue by maximebilliau** [teymour/attestation-covid19#19]
Hello, j'ai un soucis avec l'installation, j'ai fait l'installation cgi, lorsque je lance l'url j'ai un PDF vide. Donc j'ai voulu le lancer depuis le serveur directement et en effet, j'ai des erreurs

`root@ns3079017:/var/www/attestation-covid19# make clean ; make
rm -f build/* attestation.pdf
bash templates/config_avec_multimotifs.sh config/config.inc > build/config.inc
bash -c "source build/config.inc ; cat templates/qr.txt.tmpl | envsubst | tr -d '\n'  | sed 's/;/;\n/g' > build/qr.txt"
cat build/qr.txt | qr > build/qr.png
Traceback (most recent call last):
  File "/usr/bin/qr", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
Makefile:32: recipe for target 'build/qr.png' failed
make: *** [build/qr.png] Error 1`

J'ai essayé de regarder les anciennes issues et sur internet, j'ai installé plusieurs choses mais ça ne marche toujours pas.

**Comment by teymour** [comment]
A priori il manque le packet python setuptools. Sur Debian, il s'appelle `python-setuptools`.
