### ISSUE TITLE
size attestation.pdf final 500 kb incompressible vs size attestation_etat 50kb

### ISSUE THREAD

**Issue by manfred74** [teymour/attestation-covid19#20]

**Comment by teymour** [comment]
What do ask/propose ?

**Comment by manfred74** [comment]
le fichier pdf de l’attestation est 10 fois plus grand que le ficher de l’état. J’essayer de comprendre pourquoi. j’ai fait quelques essays avec les compressions zip, et ça ne compact rien, ce qui est étonnant

**Comment by teymour** [comment]
La version automne 2020 du ministère embarque le texte (ce n'était pas le cas dans la version du premier confinement) alors que dans la version générée, le texte est une image vectorisée.
