### ISSUE TITLE
nouveau format d’attestation... mi-novembre 2020

### ISSUE THREAD

**Issue by JoCluzet42** [teymour/attestation-covid19#21]
Hello! 

Je sais pas si tu as eu le temps de remarquer ces quelques modifications sur l’attestation officielle, tu as prévu de modifier cela ou j’essaye de le faire de mon côté ? ( ça se tente )

**Comment by teymour** [comment]
Merci @JoCluzet42 pour l'attentitive veille.

Je vais pouvoir commiter une nouvelle version dans la journée.

**Comment by teymour** [comment]
et voilà 6367cd0 génère le nouveau format du ministère
