### ISSUE TITLE
Possibilité de gérer des Query Strings ?

### ISSUE THREAD

**Issue by JCluzet** [teymour/attestation-covid19#23]
Hello Teymour :) 

Nous revoilà parti dans un troisième confinement, et donc évidemment une troisième (et surement dernière) fois que je replonge passionnément dans ton programme.
J'avais mi en place un site internet (VeuxSortir.fr) qui permettais d'envoyer un formulaire avec ces données etc, puis j'écrivais le petit fichier config_inc et j'envoyais le lien par mail à mon ami directement.

Aujourd'hui je viens de partager le site a beaucoup de mes amies et donc j'essaye d'automatiser tout ca.. (recevoir 100 mails et faire les fichiers manuellement.. embêtant)
J'ai réussi a mettre en place un système qui génère un Query lien avec les infos d'un formulaire, je te laisse regarder ca ici :  [veuxsortir.fr/lien](http://veuxsortir.fr/lien) ca génère un lien de ce type :  http://82.165.121.231/cgi-bin/generate.sh?f=Jean+l=Dupont+b=01%2F01%2F1970+p=Lyon+a=999%20aveu%20de%20france+c=Paris+z=75001+r=travail

Je me demandais donc, si tu penses qu'il est possible de modifier ton programme pour faire en sorte que les infos passe directement dans l'URL et non par un fichier dans le cgi-bin.

De plus on y gagne en confidentialité puisque aucune info perso serait enregistré.. 
J'ai essayé de fouiller un peu dans ton programme mais un peu de mal a trouver une piste idéale.
Si tu as une idée et que tu peux m'en faire part, je serais ravis de m'investir un peu dedans histoire d'en faire un pull request.

Bon nouveau confinement a toi ;)

**Comment by teymour** [comment]
J'imagine que l'issue a été cloturée au vu des annonces du gouvernement
de renoncer aux attestation.

Ceci dit, je me permet de répondre sur le fond.

Les choix techniques que j'ai fait ne permettent pas de lancer une
génération sans passage d'arguments au serveur contrairement au choix
fait par le ministère.

Si tel est le besoin, il est préférable de s'inspirer du projet :
https://f-droid.org/packages/com.poupa.attestationdeplacement/

**Comment by JCluzet** [comment]
Hello Teymour,

Si j'ai close l'issue c'est parce que j'ai enfin réussi a le faire ^^ 
J'ai rajouté un petit Bout de C dans le programme qui récupère la query_string et qui cree un config_basic.inc a partir de celle ci.

Je te laisse regarder ce que ca donne : 

`
#include <stdio.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>

int main(int argc, char **argv)
{
	(void)argc;
	int index = 0;
	int index2 = 0;
	char *str = argv[1];
	int motif = 0;
	char files[1000];
	FILE* fichier = NULL;
	FILE* fichier2 = NULL;
	fichier2 = fopen("/root/attestation-covid19/config/savename.txt", "a");
	char *exportmotif[9] = {"export motif_travail=", "export motif_courses=", "export motif_sante=", "export motif_famille="
	, "export motif_handicap=", "export motif_sport=", "export motif_judiciaire=", "export motif_missions=", "export motif_enfants="};
	char *exporttemp = "export prenom=";
	char *exporttemp2 = "export nom=";
	char *exporttemp3 = "export naissance_date=";
	char *exporttemp4 = "export naissance_lieu=";
	char *exporttemp5 = "export adresse=";
	char *exporttemp6 = "export fait_lieu=";
	char *exporttemp7 = "export fait_date=\"`date +\"%d/%m/%Y\"`\"\nexport fait_heures=\"`date +\"%H\"`\"\nexport fait_minutes=\"`date +\"%M\"`\"\nexport creation_date=\"`date --date=\"16 minutes ago\" +\"%d/%m/%Y\"`\"\nexport creation_heures=\"`date --date=\"16 minutes ago\" +\"%H\"`\"\nexport creation_minutes=\"`date --date=\"16 minutes ago\" +\"%M\"`\"";
	while(exporttemp[index])                         ///PRENOM
	{
		files[index2] = exporttemp[index];
		index2++;
		index++;
	}
	files[index2] = '"';
	index = 2;
	index2++;
	while(str[index] != '+')
	{
		if (str[index] == '%' && str[index + 1] == '2' && str[index + 2] == '0')
		{
			files[index2] = ' ';
			index++;
			index++;
		}
		else if (str[index] == '%' && str[index + 1] == 'C' && str[index + 2] == '3' && str[index + 3] == '%' && str[index + 4] == 'A')
		{
			files[index2] = 'e';
			index += 5;
		}
		else
			files[index2] = str[index];
		fputc(files[index2], fichier2);
		index2++;
		index++;
	}
	files[index2] = '"';
	index2++;
	files[index2] = '\n';
	index2++;

	fputc(' ', fichier2);


	index = 0;                                 ///          NOM
	while(exporttemp2[index])
	{
		files[index2] = exporttemp2[index];
		index2++;
		index++;
	}
	files[index2] = '"';
	index2++;

	index = 0;
	while (!(str[index - 2] == 'l' && str[index - 1] == '='))
		index++;
	while (str[index] != '+')
	{
		if (str[index] == '%' && str[index + 1] == '2' && str[index + 2] == '0')
		{
			files[index2] = ' ';
			index++;
			index++;
		}
		else if (str[index] == '%' && str[index + 1] == 'C' && str[index + 2] == '3' && str[index + 3] == '%' && str[index + 4] == 'A')
		{
			files[index2] = 'e';
			index += 5;
		}
		else
			files[index2] = str[index];
		fputc(files[index2], fichier2);
		index++;
		index2++;
	}
	files[index2] = '"';
	index2++;
	files[index2] = '\n';
	index2++;

	int h, min, s, day, mois, an;
	time_t now;
	time(&now);
	fprintf(fichier2, "     > %s", ctime(&now));

	fputc('\n', fichier2);
	index = 0;                                      ///          DATE DE NAISSANCE
	while(exporttemp3[index])
	{
		files[index2] = exporttemp3[index];
		index2++;
		index++;
	}
	files[index2] = '"';
	index2++;

	index = 0;
	while (!(str[index - 2] == 'b' && str[index - 1] == '='))
		index++;
	while (str[index] != '+')
	{
		if (str[index] == '%' && str[index + 1] == '2' && str[index + 2] == 'F')
		{
			files[index2] = '/';
			index++;
			index++;
		}
		else
			files[index2] = str[index];
		index++;
		index2++;
	}
	files[index2] = '"';
	index2++;
	files[index2] = '\n';
	index2++;

	index = 0;                                      ///          LIEU DE NAISSANCE
	while(exporttemp4[index])
	{
		files[index2] = exporttemp4[index];
		index2++;
		index++;
	}
	files[index2] = '"';
	index2++;

	index = 0;
	while (!(str[index - 2] == 'p' && str[index - 1] == '='))
		index++;
	while (str[index] != '+')
	{
		if (str[index] == '%' && str[index + 1] == '2' && str[index + 2] == '0')
		{
			files[index2] = ' ';
			index++;
			index++;
		}
		else if (str[index] == '%' && str[index + 1] == 'C' && str[index + 2] == '3' && str[index + 3] == '%' && str[index + 4] == 'A')
		{
			files[index2] = 'e';
			index += 5;
		}
		else
			files[index2] = str[index];
		index++;
		index2++;
	}
	files[index2] = '"';
	index2++;
	files[index2] = '\n';
	index2++;

	index = 0;                                          ///          ADRESSE
	while(exporttemp5[index])
	{
		files[index2] = exporttemp5[index];
		index2++;
		index++;
	}
	files[index2] = '"';
	index2++;

	index = 0;
	while (!(str[index - 2] == 'a' && str[index - 1] == '='))
		index++;
	while (str[index] != '+')
	{
		if (str[index] == '%' && str[index + 1] == '2' && str[index + 2] == '0')
		{
			files[index2] = ' ';
			index++;
			index++;
		}
		else if (str[index] == '%' && str[index + 1] == 'C' && str[index + 2] == '3' && str[index + 3] == '%' && str[index + 4] == 'A')
		{
			files[index2] = 'e';
			index += 5;
		}
		else
			files[index2] = str[index];
		index++;
		index2++;
	}
	files[index2] = '"';
	index2++;
	files[index2] = '\n';
	index2++;
			                                          ///          MOTIF(9 lignes)

	index = 0;
	while (!(str[index - 2] == 'r' && str[index - 1] == '='))
		index++;
	if (str[index] == '0')
		motif = -1;
	if (str[index] == 't' && str[index + 1] == 'r' && str[index + 2] == 'a' && str[index + 3] == 'v')
		motif = 0;
	if (str[index] == 'c' && str[index + 1] == 'o' && str[index + 2] == 'u' && str[index + 3] == 'r')
		motif = 1;
	if (str[index] == 's' && str[index + 1] == 'a' && str[index + 2] == 'n' && str[index + 3] == 't')
		motif = 2;
	if (str[index] == 'f' && str[index + 1] == 'a' && str[index + 2] == 'm' && str[index + 3] == 'i')
		motif = 3;
	if (str[index] == 'h' && str[index + 1] == 'a' && str[index + 2] == 'n' && str[index + 3] == 'd')
		motif = 4;
	if (str[index] == 'a' && str[index + 1] == 'n' && str[index + 2] == 'i' && str[index + 3] == 'm')
		motif = 5;
	if (str[index] == 'c' && str[index + 1] == 'o' && str[index + 2] == 'n' && str[index + 3] == 'v')
		motif = 6;
	if (str[index] == 'm' && str[index + 1] == 'i' && str[index + 2] == 's' && str[index + 3] == 's')
		motif = 7;
	if (str[index] == 'e' && str[index + 1] == 'n' && str[index + 2] == 'f' && str[index + 3] == 'a')
		motif = 8;
	int motiftemp = 0;
	int indexmot = 0;
	while( indexmot < 9 )
	{
		index = 0;
		while(exportmotif[indexmot][index])
		{
			files[index2] = exportmotif[indexmot][index];
			index2++;
			index++;
		}
		files[index2] = '"';
		index2++;
		if ( motif == indexmot )
		{
			files[index2] = 'x';
			index2++;
		}
		files[index2] = '"';
		index2++;
		files[index2] = '\n';
		index2++;
		indexmot++;
	}
	index = 0;

	while(exporttemp6[index])                         /// FAIT_LIEU
	{
		files[index2] = exporttemp6[index];
		index2++;
		index++;
	}
	files[index2] = '"';
	index2++;
	index = 0;
	while (!(str[index - 2] == 'c' && str[index - 1] == '='))
		index++;
	while(str[index] != '+')
	{
		if (str[index] == '%' && str[index + 1] == '2' && str[index + 2] == '0')
		{
			files[index2] = ' ';
			index++;
			index++;
		}
		else if (str[index] == '%' && str[index + 1] == 'C' && str[index + 2] == '3' && str[index + 3] == '%' && str[index + 4] == 'A')
		{
			files[index2] = 'e';
			index += 5;
		}
		else
			files[index2] = str[index];
		index2++;
		index++;
	}
	files[index2] = '"';
	index2++;
	files[index2] = '\n';
	index2++;

	index = 0;

	while(exporttemp7[index])                         /// HEURES
	{
		files[index2] = exporttemp7[index];
		index2++;
		index++;
	}
	files[index2] = '\0';


    fichier = fopen("/root/attestation-covid19/config/config_basic.inc", "w+");

	fprintf(fichier, "%s", files);
	fclose(fichier);
	fclose(fichier2);
	return (0);
}`

Ce petit bout de code prend en paramètre une Query_String de type f=Jean+l=Dupont+b=01%2F01%2F1970+p=Lyon+a=999%20aveu%20de%20france+c=Paris+z=75001+r=travail

et crée avec un fichier config_basic.inc comportant les infos de l'URL pour ensuite générer l'attestation.
Je te laisse regarder le résultat final ici : veuxsortir.fr/lien

Big Thanks !
