### ISSUE TITLE
Documenter la création d'une nouvelle attestation

### ISSUE THREAD

**Issue by bortzmeyer** [teymour/attestation-covid19#3]
Peut-être documenter qu'il faut faire un `make clean ` avant de `make`, quand on veut une nouvelle attestation ? (Et il peut être nécessaire d'éditer `config.inc ` également.)

**Comment by teymour** [comment]
Effectivement, il peut avoir besoin de faire un ``make clean``, j'ai essayé : 
 - de générer automatiquement le cas d'une conf avec date automatique : bd76063d68fa5765af96ae678031310c8fc66d57
 - de permettre de rappeler le configurateur : 9f33be3c564b6354e79c6e9e5c9d560682d19069

Et j'ai mis un message pour expliquer quand on besoin de faire un ``clean`` : 1b4f85693c459d8788a1ceb3288cd32dce817e9a

Après c'est peut être trop compliqué de rentrer dans ces détails. Et dire simplement « faites ``make clean ; make`` » c'est peut être mieux...
