### ISSUE TITLE
Pas de motifs multiples dans le Qrcode

### ISSUE THREAD

**Issue by deFredoo** [teymour/attestation-covid19#4]
Si on choisi deux motifs de sortie la partie textuelle est ok, mais une seule apparaît dans le QR code. Apparement pour le QR il prends que la variable "motifs_join". Ne serait-ce pas plus malin de récupérer celles renseignées pour la partie texte ?

**Comment by teymour** [comment]
Le gérérateur de configuration gère les cas de motifs multiples.

Ca serait effectivement plus simple de le gérer dans cette variable, mais avec le moteur de template (celui de gettext) que j'utilise je n'ai pas trouvé comment le faire :( Du coup, j'ai fait cette solution de facilité de "dupliquer" l'info... Si tu as une idée, je suis preneur !

**Comment by teymour** [comment]
J'ai trouvé une solution : 2f7a39f :)
