### ISSUE TITLE
Spécifier un fichier de conf dans la commande

### ISSUE THREAD

**Issue by deFredoo** [teymour/attestation-covid19#5]
Plus une question qu'une issue. Se serait cool de pouvoir spécifier un fichier de conf avec le make pour pouvoir générer rapidement une attestation pour plusieurs membres de la famille. J'essaie de le faire moi même si j'arrive à comprendre le code un peu mieux (je suis pas super doué en shell et autres)

**Comment by teymour** [comment]
Oui, c'est possible.

Avec 4909eae, j'ai modifié le [README](https://github.com/teymour/attestion-covid19/blob/master/README.md#peut-on-utiliser-un-autre-fichier-de-configuration-que-configinc-) pour documenter comment le faire (et corrigé un petit bug lié à ça ;) )
