### ISSUE TITLE
erreur make : qr not found

### ISSUE THREAD

**Issue by ghost** [teymour/attestation-covid19#8]
`cat build/qr.txt | qr > build/qr.png
/bin/sh: 1: qr: not found
make: *** [Makefile:31: build/qr.png] Error 127`

testé sours debian buster

**Comment by teymour** [comment]
Est ce que ``python-qrcode`` est installé ?

Si oui, je veux bien connaître la distribution utilisée.

Le paquet est installable au pire via un virtualenv python, comme indiqué ici : #6

**Comment by teymour** [comment]
Nous avons la même distribution.

Je pense donc que les dépendances ne sont pas installées (``python-qrcode`` notamment).

Une fois installé, le paquet va créer une commande ``qr`` qui fait référence à ``python2-qr`` :

    $ ls -l /usr/bin/qr /etc/alternatives/qr /usr/bin/python2-qr
    lrwxrwxrwx 1 root root  20 avril  6 11:43 /usr/bin/qr -> /etc/alternatives/qr
    lrwxrwxrwx 1 root root  19 avril  6 11:43 /etc/alternatives/qr -> /usr/bin/python2-qr
    -rwxr-xr-x 1 root root 365 janv. 29  2019 /usr/bin/python2-qr

Au pire, si ce binaire est ailleurs, une variable ``qr_bin`` permet d'en indiquer le chemin (soit en éditant le Makefile, soit en passant par une variable d'environnement et ``make -e``)

**Comment by ghost** [comment]
Yes je confirme `python-qrcode` n'etait pas installé .
 
Merci pour votre outil.
