### ISSUE TITLE
Erreur make test

### ISSUE THREAD

**Issue by vchatela** [teymour/attestation-covid19#9]
Bonjour,
J'ai essayé le make test mais : 
1. J'ai été surpris que le fichier de config de test ne soit pas pris en compte par défaut (du coup je ne savais pas quel prénom etc. renseigner
2. Une erreur se produit : 
```
diff build/pdf_page-0.txt build/pdforiginal_page-0.txt && echo QRCODE page 1 OK
1c1
< QR-Code:Cree le: 07/04/2020 a 13h20; Nom: Jean; Prenom: Dupont; Naissance: 01/01/1970 a Lyon; Adresse: 999 avenue de france 75001 Paris; Sortie: 07/04/2020 a 13h20; Motifs: travail-courses
---
> QR-Code:Cree le: 07/04/2020 a 13h20; Nom: Dupont; Prenom: Jean; Naissance: 01/01/1970 a Lyon; Adresse: 999 avenue de france 75001 Paris; Sortie: 07/04/2020 a 13h20; Motifs: travail-courses
Makefile:61 : la recette pour la cible « testqrcode » a échouée
```

Sinon super boulot et merci ! :)

**Comment by vchatela** [comment]
Pour le point 1. je contourne par `make clean ; config_file=config/config_test.inc make test -e`

**Comment by teymour** [comment]
Merci Valentin pour ce bug report.

Je viens de trouver une solution pour que le fichier de config soit généré.
